kind: Deployment
apiVersion: apps/v1
metadata:
  name: helm-ui-deployment
  labels:
    app: helm-ui
spec:
  selector:
    matchLabels:
      app: helm-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: helm-ui
        version: v1
    spec:
      containers:
        - name: helm-ui
          image: "fra.ocir.io/frsxwtjslf35/warp/helm-ui:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL_GRAAL
              value: http://warp-engine-graal.micro.ivandelic.com/universe/traverse
            - name: REACT_APP_API_URL_C2
              value: http://warp-engine-c2.micro.ivandelic.com/universe/traverse
            - name: REACT_APP_API_URL_NATIVE
              value: http://warp-engine-native.micro.ivandelic.com/universe/traverse
      imagePullSecrets:
        - name: ocirsecret
      nodeSelector:
        internal_addr: 10.20.10.89
---
kind: Service
apiVersion: v1
metadata:
  name: helm-ui-service
spec:
  type: ClusterIP
  selector:
    app: helm-ui
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helm-ui-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "helm-ui.micro.ivandelic.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: helm-ui-service
                port:
                  number: 3000